"""empty message

Revision ID: 1c54089222f3
Revises: e9cefd29e7fb
Create Date: 2021-05-15 13:20:20.906538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c54089222f3'
down_revision = 'e9cefd29e7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_quiz')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_maxscore', sa.Integer(), nullable=True))
        batch_op.drop_column('quizscore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quizscore', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quiz_maxscore')

    op.create_table('completed_quiz',
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
