"""empty message

Revision ID: 349010dd00db
Revises: bd99be004622
Create Date: 2021-05-16 06:06:17.848143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349010dd00db'
down_revision = 'bd99be004622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quizurl', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_quiz_quizurl'), ['quizurl'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_quizurl'))
        batch_op.drop_column('quizurl')

    # ### end Alembic commands ###
