"""empty message

Revision ID: 354420a3998f
Revises: 71395ceb44f3
Create Date: 2021-05-15 11:42:25.856868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354420a3998f'
down_revision = '71395ceb44f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complete_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('quiz_maxscore', sa.Integer(), nullable=True),
    sa.Column('quiz_attemptscore', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['quiz_maxscore'], ['quiz.quiz_maxscore'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complete_quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complete_quiz_timestamp'), ['timestamp'], unique=False)

    op.drop_table('completed_quiz')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_timestamp')
        batch_op.drop_index('ix_quiz_quizname')
        batch_op.create_index(batch_op.f('ix_quiz_quizname'), ['quizname'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_quiz_quizname'))
        batch_op.create_index('ix_quiz_quizname', ['quizname'], unique=1)
        batch_op.create_index('ix_quiz_timestamp', ['timestamp'], unique=False)

    op.create_table('completed_quiz',
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('complete_quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complete_quiz_timestamp'))

    op.drop_table('complete_quiz')
    # ### end Alembic commands ###
