"""empty message

Revision ID: 37ff4d3e1a2c
Revises: aa58c25c3c9b
Create Date: 2021-05-15 13:30:30.406247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ff4d3e1a2c'
down_revision = 'aa58c25c3c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizname', sa.String(length=128), nullable=True),
    sa.Column('quiz_maxscore', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz2_quizname'), ['quizname'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz2_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_maxscore', sa.Integer(), nullable=True))
        batch_op.drop_column('quizscore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quizscore', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quiz_maxscore')

    with op.batch_alter_table('quiz2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz2_timestamp'))
        batch_op.drop_index(batch_op.f('ix_quiz2_quizname'))

    op.drop_table('quiz2')
    # ### end Alembic commands ###
