"""empty message

Revision ID: 38ebaddb5d86
Revises: 01cfa48a6eb7
Create Date: 2021-05-16 04:10:24.939378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ebaddb5d86'
down_revision = '01cfa48a6eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_scoreoutofhundred', sa.Integer(), nullable=True))
        batch_op.drop_column('scoreoutofhundred')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoreoutofhundred', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quiz_scoreoutofhundred')

    # ### end Alembic commands ###
