"""empty message

Revision ID: 578ca2ba3f5e
Revises: 4465ec439e1e
Create Date: 2021-05-15 06:05:34.379558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578ca2ba3f5e'
down_revision = '4465ec439e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_course_timestamp'), 'course', ['timestamp'], unique=False)
    op.add_column('enrolled_course', sa.Column('course_name', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'enrolled_course', type_='foreignkey')
    op.create_foreign_key(None, 'enrolled_course', 'course', ['course_name'], ['coursename'])
    op.drop_column('enrolled_course', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrolled_course', sa.Column('course_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'enrolled_course', type_='foreignkey')
    op.create_foreign_key(None, 'enrolled_course', 'course', ['course_id'], ['id'])
    op.drop_column('enrolled_course', 'course_name')
    op.drop_index(op.f('ix_course_timestamp'), table_name='course')
    # ### end Alembic commands ###
