"""empty message

Revision ID: a79dc3a3c3fe
Revises: 349010dd00db
Create Date: 2021-05-16 19:15:01.979301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79dc3a3c3fe'
down_revision = '349010dd00db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(length=128), nullable=True),
    sa.Column('courseurl', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_coursename'), ['coursename'], unique=True)
        batch_op.create_index(batch_op.f('ix_course_courseurl'), ['courseurl'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('enrolled_course',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizname', sa.String(length=128), nullable=True),
    sa.Column('quizurl', sa.String(length=128), nullable=True),
    sa.Column('quiz_scoreoutofhundred', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_quizname'), ['quizname'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_quizurl'), ['quizurl'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_timestamp'))
        batch_op.drop_index(batch_op.f('ix_quiz_quizurl'))
        batch_op.drop_index(batch_op.f('ix_quiz_quizname'))

    op.drop_table('quiz')
    op.drop_table('enrolled_course')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_courseurl'))
        batch_op.drop_index(batch_op.f('ix_course_coursename'))

    op.drop_table('course')
    # ### end Alembic commands ###
