"""empty message

Revision ID: ad9b04bf4689
Revises: 252580455942
Create Date: 2021-05-07 00:07:55.183308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9b04bf4689'
down_revision = '252580455942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_quiz',
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('enrolled_course',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('quizes')
    op.drop_table('courses')
    op.add_column('course', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_course_timestamp'), 'course', ['timestamp'], unique=False)
    op.add_column('quiz', sa.Column('quizscore', sa.Integer(), nullable=True))
    op.add_column('quiz', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_quiz_timestamp'), 'quiz', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_timestamp'), table_name='quiz')
    op.drop_column('quiz', 'timestamp')
    op.drop_column('quiz', 'quizscore')
    op.drop_index(op.f('ix_course_timestamp'), table_name='course')
    op.drop_column('course', 'timestamp')
    op.create_table('courses',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('quizes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'quiz_id')
    )
    op.drop_table('enrolled_course')
    op.drop_table('completed_quiz')
    # ### end Alembic commands ###
