"""empty message

Revision ID: af74ac1988a7
Revises: d3a4f7c2a87e
Create Date: 2021-05-15 13:32:49.637032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af74ac1988a7'
down_revision = 'd3a4f7c2a87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizname', sa.String(length=128), nullable=True),
    sa.Column('quiz_maxscore', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_quizname'), ['quizname'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('quiz2', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz2_quizname')
        batch_op.drop_index('ix_quiz2_timestamp')

    op.drop_table('quiz2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quizname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('quiz_maxscore', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz2', schema=None) as batch_op:
        batch_op.create_index('ix_quiz2_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_quiz2_quizname', ['quizname'], unique=1)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_timestamp'))
        batch_op.drop_index(batch_op.f('ix_quiz_quizname'))

    op.drop_table('quiz')
    # ### end Alembic commands ###
