"""empty message

Revision ID: b47c9f0ff80c
Revises: 354420a3998f
Create Date: 2021-05-15 12:43:48.388704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47c9f0ff80c'
down_revision = '354420a3998f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complete_quiz', schema=None) as batch_op:
        batch_op.drop_index('ix_complete_quiz_timestamp')

    op.drop_table('complete_quiz')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_scoreoutofhundred', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quiz_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('quiz_maxscore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_maxscore', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quiz_timestamp'))
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('quiz_scoreoutofhundred')

    op.create_table('complete_quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.Column('quiz_maxscore', sa.INTEGER(), nullable=True),
    sa.Column('quiz_attemptscore', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['quiz_maxscore'], ['quiz.quiz_maxscore'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complete_quiz', schema=None) as batch_op:
        batch_op.create_index('ix_complete_quiz_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
