"""empty message

Revision ID: b5b05b5b10c9
Revises: 2909a68a12d6
Create Date: 2021-05-15 08:23:21.118868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b05b5b10c9'
down_revision = '2909a68a12d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_quiz', schema=None) as batch_op:
        batch_op.drop_column('quiz_score')

    # ### end Alembic commands ###
