"""empty message

Revision ID: d3a4f7c2a87e
Revises: 77080eab5b26
Create Date: 2021-05-15 13:32:10.426171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a4f7c2a87e'
down_revision = '77080eab5b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizname', sa.String(length=128), nullable=True),
    sa.Column('quiz_maxscore', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_quizname'), ['quizname'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_timestamp'))
        batch_op.drop_index(batch_op.f('ix_quiz_quizname'))

    op.drop_table('quiz')
    # ### end Alembic commands ###
