"""empty message

Revision ID: e01e2d282aa5
Revises: b4147ee7fe73
Create Date: 2021-05-15 06:21:44.961095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01e2d282aa5'
down_revision = 'b4147ee7fe73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_name'], ['coursename'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolled_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
