"""empty message

Revision ID: f295bdd90c2a
Revises: 24fdb8729c7c
Create Date: 2021-05-15 06:28:52.630753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f295bdd90c2a'
down_revision = '24fdb8729c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrolled_course', sa.Column('course_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'enrolled_course', type_='foreignkey')
    op.create_foreign_key(None, 'enrolled_course', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###
